#!/bin/bash
# Quick Start Guide for Nominal Trajectory Reconstruction

echo "================================================================================"
echo "                        QUICK START GUIDE"
echo "================================================================================"
echo ""
echo "Three simple steps to reconstruct and analyze your nominal trajectory:"
echo ""
echo "================================================================================"
echo "STEP 1: Generate Identification Data"
echo "================================================================================"
echo ""
echo "  In terminal 1 (with ROS running):"
echo "  $ cd /home/bryansgue/catkin_ws/src/dual_quaternion/scripts/MPC_LIE_FINAL"
echo "  $ python3 MPC2.py"
echo ""
echo "  Wait for completion..."
echo "  Output: Dual_cost_identification.mat (X, u, t, X_d)"
echo ""
echo ""
echo "================================================================================"
echo "STEP 2: Reconstruct Nominal Trajectory"
echo "================================================================================"
echo ""
echo "  In terminal 2 (no ROS needed):"
echo "  $ cd /home/bryansgue/catkin_ws/src/dual_quaternion/scripts/MPC_LIE_FINAL"
echo "  $ python3 reconstruct_nominal_trajectory.py"
echo ""
echo "  This script:"
echo "    • Loads X, u, t, X_d from identification data"
echo "    • For each time step k:"
echo "      - Takes X(:,k) as initial state"
echo "      - Uses u(:,k) as control input"
echo "      - Integrates dual quaternion dynamics with RK4"
echo "      - Produces X_nom(:,k+1)"
echo "    • Saves X, X_nom, error to new .mat file"
echo ""
echo "  Output: Dual_cost_identification_with_nominal.mat"
echo ""
echo ""
echo "================================================================================"
echo "STEP 3: Analyze Results"
echo "================================================================================"
echo ""
echo "  Option A: MATLAB (Recommended - generates plots)"
echo "  $ matlab"
echo "  >> cd /home/bryansgue/catkin_ws/src/dual_quaternion/scripts/MPC_LIE_FINAL"
echo "  >> analyze_nominal_reconstruction"
echo ""
echo "  Option B: Python (Quick statistics)"
echo "  $ python3 example_identification_workflow.py"
echo ""
echo ""
echo "================================================================================"
echo "DATA INTERPRETATION"
echo "================================================================================"
echo ""
echo "State Vector (14D):"
echo "  [1-4]:    Quaternion real part       [qw, qx, qy, qz]"
echo "  [5-8]:    Quaternion dual part       [dw, dx, dy, dz]"
echo "  [9-11]:   Angular velocity           [wx, wy, wz]"
echo "  [12-14]:  Linear velocity            [vx, vy, vz]"
echo ""
echo "Comparison:"
echo "  X       = Plant states from simulator"
echo "  X_nom   = Reconstructed from model integration"
echo "  error   = X - X_nom (measure of model accuracy)"
echo ""
echo "Check:"
echo "  • error in vx, vy, vz (indices 12-14)"
echo "  • error in wx, wy, wz (indices 9-11)"
echo "  • error growth over time"
echo ""
echo ""
echo "================================================================================"
echo "KEY CONCEPTS"
echo "================================================================================"
echo ""
echo "Why Reconstruct X_nom?"
echo "  • Simulator state X comes from real/simulated dynamics"
echo "  • Model state X_nom comes from our assumed dynamics model"
echo "  • Comparing X vs X_nom shows where model differs from reality"
echo "  • Error X - X_nom identifies what's missing in the model"
echo ""
echo "Step-by-Step Reconstruction:"
echo "  • X_nom(:,k+1) depends ONLY on X(:,k) and u(:,k)"
echo "  • NOT on previous X_nom(:,k)"
echo "  • This is like asking: 'If state was X(:,k), what would happen in next step?'"
echo ""
echo "RK4 Integration:"
echo "  • Uses 4th-order Runge-Kutta for accuracy"
echo "  • Integrates dual quaternion kinematics"
echo "  • Updates both orientation (quaternion) and position (dual part)"
echo ""
echo ""
echo "================================================================================"
echo "WHAT IF..."
echo "================================================================================"
echo ""
echo "Error is HIGH in linear velocities (vx, vy, vz):"
echo "  → Model assumes constant velocity (kinematic)"
echo "  → Real system has acceleration from control inputs"
echo "  → SOLUTION: Add dynamics dv/dt = (F/m) - (damping*v)"
echo ""
echo "Error is HIGH in angular velocities (wx, wy, wz):"
echo "  → Model doesn't include torque effects"
echo "  → SOLUTION: Add dw/dt = (1/I)*τ - (friction*w)"
echo ""
echo "Error GROWS over time:"
echo "  → Model drifts from reality"
echo "  → Check quaternion normalization"
echo "  → May need state feedback correction"
echo ""
echo "Error is SMALL (good):"
echo "  → Kinematic model is accurate for your trajectory"
echo "  → Can use for control design"
echo "  → Compare multiple trajectories for validation"
echo ""
echo ""
echo "================================================================================"
echo "FILES GENERATED"
echo "================================================================================"
echo ""
echo "From MPC2.py:"
echo "  Dual_cost_identification.mat"
echo "    └─ Contains: X, X_d, u, t, F, M, costs, KKT values"
echo ""
echo "From reconstruct_nominal_trajectory.py:"
echo "  Dual_cost_identification_with_nominal.mat"
echo "    └─ Contains: X, X_nom, X_d, u, t, error, error_norm"
echo ""
echo "Analysis:"
echo "  analyze_nominal_reconstruction.m    (MATLAB - visual analysis)"
echo "  example_identification_workflow.py  (Python - quick stats)"
echo ""
echo ""
echo "================================================================================"
echo "DOCUMENTATION"
echo "================================================================================"
echo ""
echo "For detailed information, see:"
echo "  • README_NOMINAL_RECONSTRUCTION.md    (Complete reference)"
echo "  • NOMINAL_RECONSTRUCTION_SUMMARY.txt  (Theory and background)"
echo "  • Inside Python scripts               (Code comments)"
echo ""
echo ""
echo "================================================================================"
echo "                           READY TO START!"
echo "================================================================================"
echo ""
