/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[4] = {0, 1, 0, 0};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

static const casadi_real casadi_c0[3] = {-3.7878787878787881e+02, -3.7878787878787881e+02, -2.0161290322580646e+02};
static const casadi_real casadi_c1[9] = {2.6400000000000000e-03, 0., 0., 0., 2.6400000000000000e-03, 0., 0., 0., 4.9600000000000000e-03};
static const casadi_real casadi_c2[3] = {3.7878787878787881e+02, 3.7878787878787881e+02, 2.0161290322580646e+02};
static const casadi_real casadi_c3[3] = {0., 0., 1.};

/* f_quat:(i0[8])->(o0[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  return 0;
}

/* f_rot_inv:(i0[4],i1[3])->(o0[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, *w2=w+12, w3, w4, w5, w6, *w7=w+20, w8, w9, *w10=w+26, *w11=w+30, *w12=w+34, *w13=w+38, *w14=w+54, *w15=w+70;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 4, w2);
  /* #3: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #4: @4 = @2[1] */
  for (rr=(&w4), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #5: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #6: @6 = @2[3] */
  for (rr=(&w6), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #7: @7 = horzcat(@3, @4, @5, @6) */
  rr=w7;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #8: @7 = @7' */
  /* #9: @3 = (-@4) */
  w3 = (- w4 );
  /* #10: @8 = @2[0] */
  for (rr=(&w8), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #11: @9 = (-@5) */
  w9 = (- w5 );
  /* #12: @10 = horzcat(@3, @8, @6, @9) */
  rr=w10;
  *rr++ = w3;
  *rr++ = w8;
  *rr++ = w6;
  *rr++ = w9;
  /* #13: @10 = @10' */
  /* #14: @6 = (-@6) */
  w6 = (- w6 );
  /* #15: @8 = @2[0] */
  for (rr=(&w8), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #16: @11 = horzcat(@9, @6, @8, @4) */
  rr=w11;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w4;
  /* #17: @11 = @11' */
  /* #18: @9 = @2[0] */
  for (rr=(&w9), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #19: @12 = horzcat(@6, @5, @3, @9) */
  rr=w12;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #20: @12 = @12' */
  /* #21: @13 = horzcat(@7, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w7; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #22: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @6 = 0 */
  w6 = 0.;
  /* #24: @15 = input[1][0] */
  casadi_copy(arg[1], 3, w15);
  /* #25: @7 = vertcat(@6, @15) */
  rr=w7;
  *rr++ = w6;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #26: @1 = mac(@14,@7,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w7+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #27: @6 = @1[0] */
  for (rr=(&w6), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #28: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #29: @5 = (-@5) */
  w5 = (- w5 );
  /* #30: @3 = @1[2] */
  for (rr=(&w3), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #31: @3 = (-@3) */
  w3 = (- w3 );
  /* #32: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #33: @9 = (-@9) */
  w9 = (- w9 );
  /* #34: @7 = horzcat(@6, @5, @3, @9) */
  rr=w7;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #35: @7 = @7' */
  /* #36: @6 = @1[1] */
  for (rr=(&w6), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #37: @5 = @1[0] */
  for (rr=(&w5), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #38: @3 = @1[3] */
  for (rr=(&w3), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #39: @3 = (-@3) */
  w3 = (- w3 );
  /* #40: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #41: @10 = horzcat(@6, @5, @3, @9) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #42: @10 = @10' */
  /* #43: @6 = @1[2] */
  for (rr=(&w6), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #44: @5 = @1[3] */
  for (rr=(&w5), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #45: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #46: @9 = @1[1] */
  for (rr=(&w9), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #47: @9 = (-@9) */
  w9 = (- w9 );
  /* #48: @11 = horzcat(@6, @5, @3, @9) */
  rr=w11;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #49: @11 = @11' */
  /* #50: @6 = @1[3] */
  for (rr=(&w6), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #51: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #52: @5 = (-@5) */
  w5 = (- w5 );
  /* #53: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #54: @9 = @1[0] */
  for (rr=(&w9), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #55: @1 = horzcat(@6, @5, @3, @9) */
  rr=w1;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #56: @1 = @1' */
  /* #57: @14 = horzcat(@7, @10, @11, @1) */
  rr=w14;
  for (i=0, cs=w7; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<4; ++i) *rr++ = *cs++;
  /* #58: @13 = @14' */
  for (i=0, rr=w13, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #59: @0 = mac(@13,@2,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w13+j, tt=w2+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #60: @15 = @0[1:4] */
  for (rr=w15, ss=w0+1; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #61: output[0][0] = @15 */
  casadi_copy(w15, 3, res[0]);
  return 0;
}

/* quadrotor_impl_dae_fun:(i0[15],i1[15],i2[5],i3[0],i4[],i5[18])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+6, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+88, *w16=w+103, *w17=w+111, *w18=w+115, *w19=w+119, *w20=w+123, *w21=w+127, *w22=w+143, *w23=w+159, *w24=w+191, *w25=w+223, *w26=w+239, *w27=w+271, *w28=w+335, w29, w30, *w31=w+401, *w32=w+409, *w33=w+424, *w34=w+427, *w35=w+430, *w36=w+433, *w37=w+442, *w38=w+445;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w8 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w9 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = input[1][10] */
  w10 = arg[1] ? arg[1][10] : 0;
  /* #11: @11 = input[1][11] */
  w11 = arg[1] ? arg[1][11] : 0;
  /* #12: @12 = input[1][12] */
  w12 = arg[1] ? arg[1][12] : 0;
  /* #13: @13 = input[1][13] */
  w13 = arg[1] ? arg[1][13] : 0;
  /* #14: @14 = input[1][14] */
  w14 = arg[1] ? arg[1][14] : 0;
  /* #15: @15 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #17: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #18: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #19: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #20: @3 = (-@2) */
  w3 = (- w2 );
  /* #21: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #22: @5 = (-@4) */
  w5 = (- w4 );
  /* #23: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #24: @7 = (-@6) */
  w7 = (- w6 );
  /* #25: @17 = horzcat(@1, @3, @5, @7) */
  rr=w17;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #26: @17 = @17' */
  /* #27: @3 = (-@6) */
  w3 = (- w6 );
  /* #28: @18 = horzcat(@2, @1, @3, @4) */
  rr=w18;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #29: @18 = @18' */
  /* #30: @3 = (-@2) */
  w3 = (- w2 );
  /* #31: @19 = horzcat(@4, @6, @1, @3) */
  rr=w19;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w3;
  /* #32: @19 = @19' */
  /* #33: @3 = (-@4) */
  w3 = (- w4 );
  /* #34: @20 = horzcat(@6, @3, @2, @1) */
  rr=w20;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w2;
  *rr++ = w1;
  /* #35: @20 = @20' */
  /* #36: @21 = horzcat(@17, @18, @19, @20) */
  rr=w21;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  /* #37: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #38: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #39: @23 = horzcat(@22, @21) */
  rr=w23;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  /* #40: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #41: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #42: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #43: @7 = (-@5) */
  w7 = (- w5 );
  /* #44: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #45: @9 = (-@8) */
  w9 = (- w8 );
  /* #46: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #47: @11 = (-@10) */
  w11 = (- w10 );
  /* #48: @17 = horzcat(@3, @7, @9, @11) */
  rr=w17;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w11;
  /* #49: @17 = @17' */
  /* #50: @7 = (-@10) */
  w7 = (- w10 );
  /* #51: @18 = horzcat(@5, @3, @7, @8) */
  rr=w18;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w8;
  /* #52: @18 = @18' */
  /* #53: @7 = (-@5) */
  w7 = (- w5 );
  /* #54: @19 = horzcat(@8, @10, @3, @7) */
  rr=w19;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w3;
  *rr++ = w7;
  /* #55: @19 = @19' */
  /* #56: @7 = (-@8) */
  w7 = (- w8 );
  /* #57: @20 = horzcat(@10, @7, @5, @3) */
  rr=w20;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w5;
  *rr++ = w3;
  /* #58: @20 = @20' */
  /* #59: @21 = horzcat(@17, @18, @19, @20) */
  rr=w21;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  /* #60: @25 = @21' */
  for (i=0, rr=w25, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #61: @23 = horzcat(@25, @22) */
  rr=w23;
  for (i=0, cs=w25; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  /* #62: @26 = @23' */
  for (i=0, rr=w26, cs=w23; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #63: @27 = horzcat(@24, @26) */
  rr=w27;
  for (i=0, cs=w24; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<32; ++i) *rr++ = *cs++;
  /* #64: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #65: @7 = 0 */
  w7 = 0.;
  /* #66: @9 = input[0][8] */
  w9 = arg[0] ? arg[0][8] : 0;
  /* #67: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #68: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #69: @13 = 0 */
  w13 = 0.;
  /* #70: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #71: @29 = input[0][12] */
  w29 = arg[0] ? arg[0][12] : 0;
  /* #72: @30 = input[0][13] */
  w30 = arg[0] ? arg[0][13] : 0;
  /* #73: @31 = vertcat(@7, @9, @11, @12, @13, @14, @29, @30) */
  rr=w31;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w29;
  *rr++ = w30;
  /* #74: @16 = mac(@28,@31,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w28+j, tt=w31+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #75: @16 = (@0*@16) */
  for (i=0, rr=w16, cs=w16; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #76: @0 = input[0][14] */
  w0 = arg[0] ? arg[0][14] : 0;
  /* #77: @32 = vertcat(@1, @2, @4, @6, @3, @5, @8, @10, @9, @11, @12, @14, @29, @30, @0) */
  rr=w32;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w0;
  /* #78: @17 = @32[:4] */
  for (rr=w17, ss=w32+0; ss!=w32+4; ss+=1) *rr++ = *ss;
  /* #79: @1 = 10 */
  w1 = 10.;
  /* #80: @2 = 1 */
  w2 = 1.;
  /* #81: @4 = ||@17||_F */
  w4 = sqrt(casadi_dot(4, w17, w17));
  /* #82: @2 = (@2-@4) */
  w2 -= w4;
  /* #83: @1 = (@1*@2) */
  w1 *= w2;
  /* #84: @17 = (@17*@1) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) *= w1;
  /* #85: @18 = zeros(4x1) */
  casadi_clear(w18, 4);
  /* #86: @31 = vertcat(@17, @18) */
  rr=w31;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  /* #87: @16 = (@16+@31) */
  for (i=0, rr=w16, cs=w31; i<8; ++i) (*rr++) += (*cs++);
  /* #88: @33 = zeros(3x1) */
  casadi_clear(w33, 3);
  /* #89: @34 = 
  [[-378.788, 00, 00], 
   [00, -378.788, 00], 
   [00, 00, -201.613]] */
  casadi_copy(casadi_c0, 3, w34);
  /* #90: @35 = zeros(3x1) */
  casadi_clear(w35, 3);
  /* #91: @36 = 
  [[0.00264, 0, 0], 
   [0, 0.00264, 0], 
   [0, 0, 0.00496]] */
  casadi_copy(casadi_c1, 9, w36);
  /* #92: @37 = @32[8:11] */
  for (rr=w37, ss=w32+8; ss!=w32+11; ss+=1) *rr++ = *ss;
  /* #93: @35 = mac(@36,@37,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w36+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #94: @1 = @35[2] */
  for (rr=(&w1), ss=w35+2; ss!=w35+3; ss+=1) *rr++ = *ss;
  /* #95: @2 = (@11*@1) */
  w2  = (w11*w1);
  /* #96: @4 = @35[1] */
  for (rr=(&w4), ss=w35+1; ss!=w35+2; ss+=1) *rr++ = *ss;
  /* #97: @6 = (@12*@4) */
  w6  = (w12*w4);
  /* #98: @2 = (@2-@6) */
  w2 -= w6;
  /* #99: @6 = @35[0] */
  for (rr=(&w6), ss=w35+0; ss!=w35+1; ss+=1) *rr++ = *ss;
  /* #100: @3 = (@12*@6) */
  w3  = (w12*w6);
  /* #101: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #102: @3 = (@3-@1) */
  w3 -= w1;
  /* #103: @4 = (@9*@4) */
  w4  = (w9*w4);
  /* #104: @6 = (@11*@6) */
  w6  = (w11*w6);
  /* #105: @4 = (@4-@6) */
  w4 -= w6;
  /* #106: @35 = vertcat(@2, @3, @4) */
  rr=w35;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  /* #107: @33 = mac(@34,@35,@33) */
  casadi_mtimes(w34, casadi_s1, w35, casadi_s0, w33, casadi_s0, w, 0);
  /* #108: @34 = zeros(3x1) */
  casadi_clear(w34, 3);
  /* #109: @35 = 
  [[378.788, 00, 00], 
   [00, 378.788, 00], 
   [00, 00, 201.613]] */
  casadi_copy(casadi_c2, 3, w35);
  /* #110: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #111: @3 = input[2][1] */
  w3 = arg[2] ? arg[2][1] : 0;
  /* #112: @4 = input[2][2] */
  w4 = arg[2] ? arg[2][2] : 0;
  /* #113: @6 = input[2][3] */
  w6 = arg[2] ? arg[2][3] : 0;
  /* #114: @1 = input[2][4] */
  w1 = arg[2] ? arg[2][4] : 0;
  /* #115: @38 = vertcat(@2, @3, @4, @6, @1) */
  rr=w38;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w1;
  /* #116: @37 = @38[1:4] */
  for (rr=w37, ss=w38+1; ss!=w38+4; ss+=1) *rr++ = *ss;
  /* #117: @34 = mac(@35,@37,@34) */
  casadi_mtimes(w35, casadi_s1, w37, casadi_s0, w34, casadi_s0, w, 0);
  /* #118: @33 = (@33+@34) */
  for (i=0, rr=w33, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #119: @3 = (@29*@12) */
  w3  = (w29*w12);
  /* #120: @4 = (@30*@11) */
  w4  = (w30*w11);
  /* #121: @3 = (@3-@4) */
  w3 -= w4;
  /* #122: @30 = (@30*@9) */
  w30 *= w9;
  /* #123: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #124: @30 = (@30-@12) */
  w30 -= w12;
  /* #125: @14 = (@14*@11) */
  w14 *= w11;
  /* #126: @29 = (@29*@9) */
  w29 *= w9;
  /* #127: @14 = (@14-@29) */
  w14 -= w29;
  /* #128: @34 = vertcat(@3, @30, @14) */
  rr=w34;
  *rr++ = w3;
  *rr++ = w30;
  *rr++ = w14;
  /* #129: @3 = 9.8 */
  w3 = 9.8000000000000007e+00;
  /* #130: @31 = @32[:8] */
  for (rr=w31, ss=w32+0; ss!=w32+8; ss+=1) *rr++ = *ss;
  /* #131: @17 = f_quat(@31) */
  arg1[0]=w31;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #132: @35 = [0, 0, 1] */
  casadi_copy(casadi_c3, 3, w35);
  /* #133: @37 = f_rot_inv(@17, @35) */
  arg1[0]=w17;
  arg1[1]=w35;
  res1[0]=w37;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #134: @37 = (@3*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #135: @34 = (@34-@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #136: @37 = [0, 0, 1] */
  casadi_copy(casadi_c3, 3, w37);
  /* #137: @37 = (@37*@2) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w2;
  /* #138: @34 = (@34+@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #139: @32 = vertcat(@16, @33, @34, @1) */
  rr=w32;
  for (i=0, cs=w16; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  *rr++ = w1;
  /* #140: @15 = (@15-@32) */
  for (i=0, rr=w15, cs=w32; i<15; ++i) (*rr++) -= (*cs++);
  /* #141: output[0][0] = @15 */
  casadi_copy(w15, 15, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    case 5: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 450;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
