/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s5[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[9] = {2.6400000000000000e-03, 0., 0., 0., 2.6400000000000000e-03, 0., 0., 0., 4.9600000000000000e-03};
static const casadi_real casadi_c2[3] = {-3.7878787878787881e+02, -3.7878787878787881e+02, -2.0161290322580646e+02};
static const casadi_real casadi_c3[3] = {3.7878787878787881e+02, 3.7878787878787881e+02, 2.0161290322580646e+02};

/* f_quat:(i0[8])->(o0[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  return 0;
}

/* adj1_f_rot_inv:(i0[4],i1[3],out_o0[3x1,0nz],adj_o0[3])->(adj_i0[4],adj_i1[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, *w2=w+12, w3, w4, w5, w6, *w7=w+20, w8, w9, *w10=w+26, *w11=w+30, *w12=w+34, *w13=w+38, *w14=w+54, *w15=w+70, *w16=w+73, *w17=w+89, w18, w19, w20, w21, w22;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 4, w2);
  /* #3: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #4: @4 = @2[1] */
  for (rr=(&w4), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #5: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #6: @6 = @2[3] */
  for (rr=(&w6), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #7: @7 = horzcat(@3, @4, @5, @6) */
  rr=w7;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #8: @7 = @7' */
  /* #9: @3 = (-@4) */
  w3 = (- w4 );
  /* #10: @8 = @2[0] */
  for (rr=(&w8), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #11: @9 = (-@5) */
  w9 = (- w5 );
  /* #12: @10 = horzcat(@3, @8, @6, @9) */
  rr=w10;
  *rr++ = w3;
  *rr++ = w8;
  *rr++ = w6;
  *rr++ = w9;
  /* #13: @10 = @10' */
  /* #14: @6 = (-@6) */
  w6 = (- w6 );
  /* #15: @8 = @2[0] */
  for (rr=(&w8), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #16: @11 = horzcat(@9, @6, @8, @4) */
  rr=w11;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w4;
  /* #17: @11 = @11' */
  /* #18: @9 = @2[0] */
  for (rr=(&w9), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #19: @12 = horzcat(@6, @5, @3, @9) */
  rr=w12;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #20: @12 = @12' */
  /* #21: @13 = horzcat(@7, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w7; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #22: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @6 = 0 */
  w6 = 0.;
  /* #24: @15 = input[1][0] */
  casadi_copy(arg[1], 3, w15);
  /* #25: @7 = vertcat(@6, @15) */
  rr=w7;
  *rr++ = w6;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #26: @1 = mac(@14,@7,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w7+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #27: @6 = @1[0] */
  for (rr=(&w6), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #28: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #29: @5 = (-@5) */
  w5 = (- w5 );
  /* #30: @3 = @1[2] */
  for (rr=(&w3), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #31: @3 = (-@3) */
  w3 = (- w3 );
  /* #32: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #33: @9 = (-@9) */
  w9 = (- w9 );
  /* #34: @10 = horzcat(@6, @5, @3, @9) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #35: @10 = @10' */
  /* #36: @6 = @1[1] */
  for (rr=(&w6), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #37: @5 = @1[0] */
  for (rr=(&w5), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #38: @3 = @1[3] */
  for (rr=(&w3), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #39: @3 = (-@3) */
  w3 = (- w3 );
  /* #40: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #41: @11 = horzcat(@6, @5, @3, @9) */
  rr=w11;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #42: @11 = @11' */
  /* #43: @6 = @1[2] */
  for (rr=(&w6), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #44: @5 = @1[3] */
  for (rr=(&w5), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #45: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #46: @9 = @1[1] */
  for (rr=(&w9), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #47: @9 = (-@9) */
  w9 = (- w9 );
  /* #48: @12 = horzcat(@6, @5, @3, @9) */
  rr=w12;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #49: @12 = @12' */
  /* #50: @6 = @1[3] */
  for (rr=(&w6), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #51: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #52: @5 = (-@5) */
  w5 = (- w5 );
  /* #53: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #54: @9 = @1[0] */
  for (rr=(&w9), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #55: @1 = horzcat(@6, @5, @3, @9) */
  rr=w1;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w9;
  /* #56: @1 = @1' */
  /* #57: @14 = horzcat(@10, @11, @12, @1) */
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<4; ++i) *rr++ = *cs++;
  /* #58: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #59: @15 = input[3][0] */
  casadi_copy(arg[3], 3, w15);
  /* #60: (@10[1:4] += @15) */
  for (rr=w10+1, ss=w15; rr!=w10+4; rr+=1) *rr += *ss++;
  /* #61: @0 = mac(@14,@10,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w10+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #62: @14 = zeros(4x4) */
  casadi_clear(w14, 16);
  /* #63: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #64: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #65: @2 = @2' */
  /* #66: @16 = mac(@10,@2,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w10+j, tt=w2+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #67: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #68: {@10, @2, @12, @1} = horzsplit(@17) */
  casadi_copy(w17, 4, w10);
  casadi_copy(w17+4, 4, w2);
  casadi_copy(w17+8, 4, w12);
  casadi_copy(w17+12, 4, w1);
  /* #69: @1 = @1' */
  /* #70: {@6, @5, @3, @9} = horzsplit(@1) */
  w6 = w1[0];
  w5 = w1[1];
  w3 = w1[2];
  w9 = w1[3];
  /* #71: (@11[0] += @9) */
  for (rr=w11+0, ss=(&w9); rr!=w11+1; rr+=1) *rr += *ss++;
  /* #72: (@11[1] += @3) */
  for (rr=w11+1, ss=(&w3); rr!=w11+2; rr+=1) *rr += *ss++;
  /* #73: @5 = (-@5) */
  w5 = (- w5 );
  /* #74: (@11[2] += @5) */
  for (rr=w11+2, ss=(&w5); rr!=w11+3; rr+=1) *rr += *ss++;
  /* #75: (@11[3] += @6) */
  for (rr=w11+3, ss=(&w6); rr!=w11+4; rr+=1) *rr += *ss++;
  /* #76: @12 = @12' */
  /* #77: {@6, @5, @3, @9} = horzsplit(@12) */
  w6 = w12[0];
  w5 = w12[1];
  w3 = w12[2];
  w9 = w12[3];
  /* #78: @9 = (-@9) */
  w9 = (- w9 );
  /* #79: (@11[1] += @9) */
  for (rr=w11+1, ss=(&w9); rr!=w11+2; rr+=1) *rr += *ss++;
  /* #80: (@11[0] += @3) */
  for (rr=w11+0, ss=(&w3); rr!=w11+1; rr+=1) *rr += *ss++;
  /* #81: (@11[3] += @5) */
  for (rr=w11+3, ss=(&w5); rr!=w11+4; rr+=1) *rr += *ss++;
  /* #82: (@11[2] += @6) */
  for (rr=w11+2, ss=(&w6); rr!=w11+3; rr+=1) *rr += *ss++;
  /* #83: @2 = @2' */
  /* #84: {@6, @5, @3, @9} = horzsplit(@2) */
  w6 = w2[0];
  w5 = w2[1];
  w3 = w2[2];
  w9 = w2[3];
  /* #85: (@11[2] += @9) */
  for (rr=w11+2, ss=(&w9); rr!=w11+3; rr+=1) *rr += *ss++;
  /* #86: @3 = (-@3) */
  w3 = (- w3 );
  /* #87: (@11[3] += @3) */
  for (rr=w11+3, ss=(&w3); rr!=w11+4; rr+=1) *rr += *ss++;
  /* #88: (@11[0] += @5) */
  for (rr=w11+0, ss=(&w5); rr!=w11+1; rr+=1) *rr += *ss++;
  /* #89: (@11[1] += @6) */
  for (rr=w11+1, ss=(&w6); rr!=w11+2; rr+=1) *rr += *ss++;
  /* #90: @10 = @10' */
  /* #91: {@6, @5, @3, @9} = horzsplit(@10) */
  w6 = w10[0];
  w5 = w10[1];
  w3 = w10[2];
  w9 = w10[3];
  /* #92: @9 = (-@9) */
  w9 = (- w9 );
  /* #93: (@11[3] += @9) */
  for (rr=w11+3, ss=(&w9); rr!=w11+4; rr+=1) *rr += *ss++;
  /* #94: @3 = (-@3) */
  w3 = (- w3 );
  /* #95: (@11[2] += @3) */
  for (rr=w11+2, ss=(&w3); rr!=w11+3; rr+=1) *rr += *ss++;
  /* #96: @5 = (-@5) */
  w5 = (- w5 );
  /* #97: (@11[1] += @5) */
  for (rr=w11+1, ss=(&w5); rr!=w11+2; rr+=1) *rr += *ss++;
  /* #98: (@11[0] += @6) */
  for (rr=w11+0, ss=(&w6); rr!=w11+1; rr+=1) *rr += *ss++;
  /* #99: @7 = @7' */
  /* #100: @14 = mac(@11,@7,@14) */
  for (i=0, rr=w14; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w11+j, tt=w7+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #101: @17 = @14' */
  for (i=0, rr=w17, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #102: {@7, @10, @2, @12} = horzsplit(@17) */
  casadi_copy(w17, 4, w7);
  casadi_copy(w17+4, 4, w10);
  casadi_copy(w17+8, 4, w2);
  casadi_copy(w17+12, 4, w12);
  /* #103: @12 = @12' */
  /* #104: {@6, @5, @3, @9} = horzsplit(@12) */
  w6 = w12[0];
  w5 = w12[1];
  w3 = w12[2];
  w9 = w12[3];
  /* #105: (@0[0] += @9) */
  for (rr=w0+0, ss=(&w9); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #106: @2 = @2' */
  /* #107: {@9, @8, @4, @18} = horzsplit(@2) */
  w9 = w2[0];
  w8 = w2[1];
  w4 = w2[2];
  w18 = w2[3];
  /* #108: (@0[0] += @4) */
  for (rr=w0+0, ss=(&w4); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #109: @10 = @10' */
  /* #110: {@4, @19, @20, @21} = horzsplit(@10) */
  w4 = w10[0];
  w19 = w10[1];
  w20 = w10[2];
  w21 = w10[3];
  /* #111: (@0[0] += @19) */
  for (rr=w0+0, ss=(&w19); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #112: @6 = (@6+@8) */
  w6 += w8;
  /* #113: @20 = (@20-@6) */
  w20 -= w6;
  /* #114: @7 = @7' */
  /* #115: {@6, @8, @19, @22} = horzsplit(@7) */
  w6 = w7[0];
  w8 = w7[1];
  w19 = w7[2];
  w22 = w7[3];
  /* #116: @20 = (@20+@22) */
  w20 += w22;
  /* #117: (@0[3] += @20) */
  for (rr=w0+3, ss=(&w20); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #118: @9 = (@9+@21) */
  w9 += w21;
  /* #119: @5 = (@5-@9) */
  w5 -= w9;
  /* #120: @5 = (@5+@19) */
  w5 += w19;
  /* #121: (@0[2] += @5) */
  for (rr=w0+2, ss=(&w5); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #122: @3 = (@3+@4) */
  w3 += w4;
  /* #123: @18 = (@18-@3) */
  w18 -= w3;
  /* #124: @18 = (@18+@8) */
  w18 += w8;
  /* #125: (@0[1] += @18) */
  for (rr=w0+1, ss=(&w18); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #126: (@0[0] += @6) */
  for (rr=w0+0, ss=(&w6); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #127: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #128: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #129: @0 = mac(@13,@11,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w13+j, tt=w11+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #130: {NULL, @15} = vertsplit(@0) */
  casadi_copy(w0+1, 3, w15);
  /* #131: output[1][0] = @15 */
  casadi_copy(w15, 3, res[1]);
  return 0;
}

/* adj1_f_quat:(i0[8],out_o0[4x1,0nz],adj_o0[4])->(adj_i0[8x1,4nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0, w1, w2, w3, w4;
  /* #0: @0 = input[2][0] */
  casadi_copy(arg[2], 4, w0);
  /* #1: {@1, @2, @3, @4} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w3 = w0[2];
  w4 = w0[3];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #5: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  return 0;
}

/* quadrotor_expl_vde_adj:(i0[15],i1[15],i2[5],i3[18])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real *w0=w+110, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, *w16=w+140, *w17=w+155, *w19=w+163, *w20=w+167, *w22=w+170, *w23=w+185, *w24=w+193, *w25=w+196, w26, *w27=w+200, *w28=w+203, *w29=w+207, *w30=w+216, *w31=w+225, *w32=w+228, *w33=w+231, w34, w35, w36, w37, w38, *w39=w+239, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, *w52=w+255, w53, w54, *w55=w+321, *w56=w+385, *w57=w+417, *w58=w+449, *w59=w+481, *w60=w+497, *w61=w+513, *w62=w+529, w63, w64, w65, w66, w67, w68, w69, w70, w71, w72, w73, *w74=w+544;
  /* #0: @0 = zeros(15x1) */
  casadi_clear(w0, 15);
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = input[0][2] */
  w3 = arg[0] ? arg[0][2] : 0;
  /* #4: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #7: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #8: @8 = input[0][7] */
  w8 = arg[0] ? arg[0][7] : 0;
  /* #9: @9 = input[0][8] */
  w9 = arg[0] ? arg[0][8] : 0;
  /* #10: @10 = input[0][9] */
  w10 = arg[0] ? arg[0][9] : 0;
  /* #11: @11 = input[0][10] */
  w11 = arg[0] ? arg[0][10] : 0;
  /* #12: @12 = input[0][11] */
  w12 = arg[0] ? arg[0][11] : 0;
  /* #13: @13 = input[0][12] */
  w13 = arg[0] ? arg[0][12] : 0;
  /* #14: @14 = input[0][13] */
  w14 = arg[0] ? arg[0][13] : 0;
  /* #15: @15 = input[0][14] */
  w15 = arg[0] ? arg[0][14] : 0;
  /* #16: @16 = vertcat(@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15) */
  rr=w16;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #17: @17 = @16[:8] */
  for (rr=w17, ss=w16+0; ss!=w16+8; ss+=1) *rr++ = *ss;
  /* #18: @18 = zeros(4x1,0nz) */
  /* #19: @19 = f_quat(@17) */
  arg1[0]=w17;
  res1[0]=w19;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: @20 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w20);
  /* #21: @21 = zeros(3x1,0nz) */
  /* #22: @15 = 9.8 */
  w15 = 9.8000000000000007e+00;
  /* #23: @22 = input[1][0] */
  casadi_copy(arg[1], 15, w22);
  /* #24: {@23, @24, @25, @26} = vertsplit(@22) */
  casadi_copy(w22, 8, w23);
  casadi_copy(w22+8, 3, w24);
  casadi_copy(w22+11, 3, w25);
  w26 = w22[14];
  /* #25: @27 = (@15*@25) */
  for (i=0, rr=w27, cs=w25; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #26: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #27: {@28, NULL} = adj1_f_rot_inv(@19, @20, @21, @27) */
  arg1[0]=w19;
  arg1[1]=w20;
  arg1[2]=0;
  arg1[3]=w27;
  res1[0]=w28;
  res1[1]=0;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: @19 = adj1_f_quat(@17, @18, @28) */
  arg1[0]=w17;
  arg1[1]=0;
  arg1[2]=w28;
  res1[0]=w19;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #29: (@0[:4] += @19) */
  for (rr=w0+0, ss=w19; rr!=w0+4; rr+=1) *rr += *ss++;
  /* #30: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #31: @29 = 
  [[0.00264, 0, 0], 
   [0, 0.00264, 0], 
   [0, 0, 0.00496]] */
  casadi_copy(casadi_c1, 9, w29);
  /* #32: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #33: @27 = zeros(3x1) */
  casadi_clear(w27, 3);
  /* #34: @31 = zeros(3x1) */
  casadi_clear(w31, 3);
  /* #35: @32 = 
  [[-378.788, 00, 00], 
   [00, -378.788, 00], 
   [00, 00, -201.613]] */
  casadi_copy(casadi_c2, 3, w32);
  /* #36: @33 = @32' */
  casadi_trans(w32,casadi_s0, w33, casadi_s0, iw);
  /* #37: @31 = mac(@33,@24,@31) */
  casadi_mtimes(w33, casadi_s0, w24, casadi_s1, w31, casadi_s1, w, 0);
  /* #38: {@15, @34, @35} = vertsplit(@31) */
  w15 = w31[0];
  w34 = w31[1];
  w35 = w31[2];
  /* #39: @36 = (@11*@34) */
  w36  = (w11*w34);
  /* #40: @37 = (@10*@35) */
  w37  = (w10*w35);
  /* #41: @36 = (@36-@37) */
  w36 -= w37;
  /* #42: (@27[0] += @36) */
  for (rr=w27+0, ss=(&w36); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #43: @36 = (@9*@35) */
  w36  = (w9*w35);
  /* #44: @37 = (@11*@15) */
  w37  = (w11*w15);
  /* #45: @36 = (@36-@37) */
  w36 -= w37;
  /* #46: (@27[1] += @36) */
  for (rr=w27+1, ss=(&w36); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #47: @36 = (@10*@15) */
  w36  = (w10*w15);
  /* #48: @37 = (@9*@34) */
  w37  = (w9*w34);
  /* #49: @36 = (@36-@37) */
  w36 -= w37;
  /* #50: (@27[2] += @36) */
  for (rr=w27+2, ss=(&w36); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #51: @20 = mac(@30,@27,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w30+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #52: (@0[8:11] += @20) */
  for (rr=w0+8, ss=w20; rr!=w0+11; rr+=1) *rr += *ss++;
  /* #53: @36 = 10 */
  w36 = 10.;
  /* #54: @37 = 1 */
  w37 = 1.;
  /* #55: @19 = @16[:4] */
  for (rr=w19, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #56: @38 = ||@19||_F */
  w38 = sqrt(casadi_dot(4, w19, w19));
  /* #57: @37 = (@37-@38) */
  w37 -= w38;
  /* #58: @37 = (@36*@37) */
  w37  = (w36*w37);
  /* #59: {@28, NULL} = vertsplit(@23) */
  casadi_copy(w23, 4, w28);
  /* #60: @39 = (@37*@28) */
  for (i=0, rr=w39, cs=w28; i<4; ++i) (*rr++)  = (w37*(*cs++));
  /* #61: @37 = dot(@19, @28) */
  w37 = casadi_dot(4, w19, w28);
  /* #62: @36 = (@36*@37) */
  w36 *= w37;
  /* #63: @36 = (@36/@38) */
  w36 /= w38;
  /* #64: @19 = (@36*@19) */
  for (i=0, rr=w19, cs=w19; i<4; ++i) (*rr++)  = (w36*(*cs++));
  /* #65: @39 = (@39-@19) */
  for (i=0, rr=w39, cs=w19; i<4; ++i) (*rr++) -= (*cs++);
  /* #66: (@0[:4] += @39) */
  for (rr=w0+0, ss=w39; rr!=w0+4; rr+=1) *rr += *ss++;
  /* #67: {@36, @38, @37, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51} = vertsplit(@0) */
  w36 = w0[0];
  w38 = w0[1];
  w37 = w0[2];
  w40 = w0[3];
  w41 = w0[4];
  w42 = w0[5];
  w43 = w0[6];
  w44 = w0[7];
  w45 = w0[8];
  w46 = w0[9];
  w47 = w0[10];
  w48 = w0[11];
  w49 = w0[12];
  w50 = w0[13];
  w51 = w0[14];
  /* #68: @52 = zeros(8x8) */
  casadi_clear(w52, 64);
  /* #69: @53 = 0.5 */
  w53 = 5.0000000000000000e-01;
  /* #70: @23 = (@53*@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) (*rr++)  = (w53*(*cs++));
  /* #71: @53 = 0 */
  w53 = 0.;
  /* #72: @54 = 0 */
  w54 = 0.;
  /* #73: @17 = vertcat(@53, @9, @10, @11, @54, @12, @13, @14) */
  rr=w17;
  *rr++ = w53;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w54;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #74: @17 = @17' */
  /* #75: @52 = mac(@23,@17,@52) */
  for (i=0, rr=w52; i<8; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w17+i*1; k<1; ++k) *rr += ss[k*8]**tt++;
  /* #76: @55 = @52' */
  for (i=0, rr=w55, cs=w52; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #77: {@56, @57} = horzsplit(@55) */
  casadi_copy(w55, 32, w56);
  casadi_copy(w55+32, 32, w57);
  /* #78: @58 = @57' */
  for (i=0, rr=w58, cs=w57; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #79: {@59, @60} = horzsplit(@58) */
  casadi_copy(w58, 16, w59);
  casadi_copy(w58+16, 16, w60);
  /* #80: @58 = @56' */
  for (i=0, rr=w58, cs=w56; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #81: {@61, NULL} = horzsplit(@58) */
  casadi_copy(w58, 16, w61);
  /* #82: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<16; ++i) (*rr++) += (*cs++);
  /* #83: @61 = @60' */
  for (i=0, rr=w61, cs=w60; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #84: {@39, @19, @28, @62} = horzsplit(@61) */
  casadi_copy(w61, 4, w39);
  casadi_copy(w61+4, 4, w19);
  casadi_copy(w61+8, 4, w28);
  casadi_copy(w61+12, 4, w62);
  /* #85: @62 = @62' */
  /* #86: {@53, @54, @63, @64} = horzsplit(@62) */
  w53 = w62[0];
  w54 = w62[1];
  w63 = w62[2];
  w64 = w62[3];
  /* #87: @36 = (@36+@64) */
  w36 += w64;
  /* #88: @28 = @28' */
  /* #89: {@64, @65, @66, @67} = horzsplit(@28) */
  w64 = w28[0];
  w65 = w28[1];
  w66 = w28[2];
  w67 = w28[3];
  /* #90: @36 = (@36+@66) */
  w36 += w66;
  /* #91: @19 = @19' */
  /* #92: {@66, @68, @69, @70} = horzsplit(@19) */
  w66 = w19[0];
  w68 = w19[1];
  w69 = w19[2];
  w70 = w19[3];
  /* #93: @36 = (@36+@68) */
  w36 += w68;
  /* #94: @39 = @39' */
  /* #95: {@68, @71, @72, @73} = horzsplit(@39) */
  w68 = w39[0];
  w71 = w39[1];
  w72 = w39[2];
  w73 = w39[3];
  /* #96: @36 = (@36+@68) */
  w36 += w68;
  /* #97: output[0][0] = @36 */
  if (res[0]) res[0][0] = w36;
  /* #98: @38 = (@38+@63) */
  w38 += w63;
  /* #99: @38 = (@38-@67) */
  w38 -= w67;
  /* #100: @38 = (@38+@66) */
  w38 += w66;
  /* #101: @38 = (@38-@71) */
  w38 -= w71;
  /* #102: output[0][1] = @38 */
  if (res[0]) res[0][1] = w38;
  /* #103: @37 = (@37-@54) */
  w37 -= w54;
  /* #104: @37 = (@37+@64) */
  w37 += w64;
  /* #105: @37 = (@37+@70) */
  w37 += w70;
  /* #106: @37 = (@37-@72) */
  w37 -= w72;
  /* #107: output[0][2] = @37 */
  if (res[0]) res[0][2] = w37;
  /* #108: @40 = (@40+@53) */
  w40 += w53;
  /* #109: @40 = (@40+@65) */
  w40 += w65;
  /* #110: @40 = (@40-@69) */
  w40 -= w69;
  /* #111: @40 = (@40-@73) */
  w40 -= w73;
  /* #112: output[0][3] = @40 */
  if (res[0]) res[0][3] = w40;
  /* #113: @61 = @59' */
  for (i=0, rr=w61, cs=w59; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #114: {@39, @19, @28, @62} = horzsplit(@61) */
  casadi_copy(w61, 4, w39);
  casadi_copy(w61+4, 4, w19);
  casadi_copy(w61+8, 4, w28);
  casadi_copy(w61+12, 4, w62);
  /* #115: @62 = @62' */
  /* #116: {@40, @73, @69, @65} = horzsplit(@62) */
  w40 = w62[0];
  w73 = w62[1];
  w69 = w62[2];
  w65 = w62[3];
  /* #117: @41 = (@41+@65) */
  w41 += w65;
  /* #118: @28 = @28' */
  /* #119: {@65, @53, @37, @72} = horzsplit(@28) */
  w65 = w28[0];
  w53 = w28[1];
  w37 = w28[2];
  w72 = w28[3];
  /* #120: @41 = (@41+@37) */
  w41 += w37;
  /* #121: @19 = @19' */
  /* #122: {@37, @70, @64, @54} = horzsplit(@19) */
  w37 = w19[0];
  w70 = w19[1];
  w64 = w19[2];
  w54 = w19[3];
  /* #123: @41 = (@41+@70) */
  w41 += w70;
  /* #124: @39 = @39' */
  /* #125: {@70, @38, @71, @66} = horzsplit(@39) */
  w70 = w39[0];
  w38 = w39[1];
  w71 = w39[2];
  w66 = w39[3];
  /* #126: @41 = (@41+@70) */
  w41 += w70;
  /* #127: output[0][4] = @41 */
  if (res[0]) res[0][4] = w41;
  /* #128: @42 = (@42+@69) */
  w42 += w69;
  /* #129: @42 = (@42-@72) */
  w42 -= w72;
  /* #130: @42 = (@42+@37) */
  w42 += w37;
  /* #131: @42 = (@42-@38) */
  w42 -= w38;
  /* #132: output[0][5] = @42 */
  if (res[0]) res[0][5] = w42;
  /* #133: @43 = (@43-@73) */
  w43 -= w73;
  /* #134: @43 = (@43+@65) */
  w43 += w65;
  /* #135: @43 = (@43+@54) */
  w43 += w54;
  /* #136: @43 = (@43-@71) */
  w43 -= w71;
  /* #137: output[0][6] = @43 */
  if (res[0]) res[0][6] = w43;
  /* #138: @44 = (@44+@40) */
  w44 += w40;
  /* #139: @44 = (@44+@53) */
  w44 += w53;
  /* #140: @44 = (@44-@64) */
  w44 -= w64;
  /* #141: @44 = (@44-@66) */
  w44 -= w66;
  /* #142: output[0][7] = @44 */
  if (res[0]) res[0][7] = w44;
  /* #143: {@44, @66, @64} = vertsplit(@25) */
  w44 = w25[0];
  w66 = w25[1];
  w64 = w25[2];
  /* #144: @53 = (@14*@66) */
  w53  = (w14*w66);
  /* #145: @40 = (@13*@64) */
  w40  = (w13*w64);
  /* #146: @53 = (@53-@40) */
  w53 -= w40;
  /* #147: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #148: @27 = @16[8:11] */
  for (rr=w27, ss=w16+8; ss!=w16+11; ss+=1) *rr++ = *ss;
  /* #149: @20 = mac(@29,@27,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #150: @40 = @20[1] */
  for (rr=(&w40), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #151: @43 = (@40*@35) */
  w43  = (w40*w35);
  /* #152: @53 = (@53+@43) */
  w53 += w43;
  /* #153: @43 = @20[2] */
  for (rr=(&w43), ss=w20+2; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #154: @71 = (@43*@34) */
  w71  = (w43*w34);
  /* #155: @53 = (@53-@71) */
  w53 -= w71;
  /* #156: @53 = (@53+@45) */
  w53 += w45;
  /* #157: @17 = zeros(8x1) */
  casadi_clear(w17, 8);
  /* #158: @45 = (-@2) */
  w45 = (- w2 );
  /* #159: @71 = (-@3) */
  w71 = (- w3 );
  /* #160: @54 = (-@4) */
  w54 = (- w4 );
  /* #161: @39 = horzcat(@1, @45, @71, @54) */
  rr=w39;
  *rr++ = w1;
  *rr++ = w45;
  *rr++ = w71;
  *rr++ = w54;
  /* #162: @39 = @39' */
  /* #163: @45 = (-@4) */
  w45 = (- w4 );
  /* #164: @19 = horzcat(@2, @1, @45, @3) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w45;
  *rr++ = w3;
  /* #165: @19 = @19' */
  /* #166: @45 = (-@2) */
  w45 = (- w2 );
  /* #167: @28 = horzcat(@3, @4, @1, @45) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w45;
  /* #168: @28 = @28' */
  /* #169: @3 = (-@3) */
  w3 = (- w3 );
  /* #170: @62 = horzcat(@4, @3, @2, @1) */
  rr=w62;
  *rr++ = w4;
  *rr++ = w3;
  *rr++ = w2;
  *rr++ = w1;
  /* #171: @62 = @62' */
  /* #172: @61 = horzcat(@39, @19, @28, @62) */
  rr=w61;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w62; i<4; ++i) *rr++ = *cs++;
  /* #173: @59 = @61' */
  for (i=0, rr=w59, cs=w61; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #174: @61 = zeros(4x4) */
  casadi_clear(w61, 16);
  /* #175: @58 = horzcat(@59, @61) */
  rr=w58;
  for (i=0, cs=w59; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w61; i<16; ++i) *rr++ = *cs++;
  /* #176: @56 = @58' */
  for (i=0, rr=w56, cs=w58; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #177: @4 = (-@6) */
  w4 = (- w6 );
  /* #178: @3 = (-@7) */
  w3 = (- w7 );
  /* #179: @2 = (-@8) */
  w2 = (- w8 );
  /* #180: @39 = horzcat(@5, @4, @3, @2) */
  rr=w39;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w3;
  *rr++ = w2;
  /* #181: @39 = @39' */
  /* #182: @4 = (-@8) */
  w4 = (- w8 );
  /* #183: @19 = horzcat(@6, @5, @4, @7) */
  rr=w19;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w7;
  /* #184: @19 = @19' */
  /* #185: @4 = (-@6) */
  w4 = (- w6 );
  /* #186: @28 = horzcat(@7, @8, @5, @4) */
  rr=w28;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w5;
  *rr++ = w4;
  /* #187: @28 = @28' */
  /* #188: @7 = (-@7) */
  w7 = (- w7 );
  /* #189: @62 = horzcat(@8, @7, @6, @5) */
  rr=w62;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w5;
  /* #190: @62 = @62' */
  /* #191: @61 = horzcat(@39, @19, @28, @62) */
  rr=w61;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w62; i<4; ++i) *rr++ = *cs++;
  /* #192: @60 = @61' */
  for (i=0, rr=w60, cs=w61; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #193: @58 = horzcat(@60, @59) */
  rr=w58;
  for (i=0, cs=w60; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<16; ++i) *rr++ = *cs++;
  /* #194: @57 = @58' */
  for (i=0, rr=w57, cs=w58; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #195: @55 = horzcat(@56, @57) */
  rr=w55;
  for (i=0, cs=w56; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w57; i<32; ++i) *rr++ = *cs++;
  /* #196: @17 = mac(@55,@23,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w55+j, tt=w23+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #197: {NULL, @8, @7, @6, NULL, @5, @4, @3} = vertsplit(@17) */
  w8 = w17[1];
  w7 = w17[2];
  w6 = w17[3];
  w5 = w17[5];
  w4 = w17[6];
  w3 = w17[7];
  /* #198: @53 = (@53+@8) */
  w53 += w8;
  /* #199: output[0][8] = @53 */
  if (res[0]) res[0][8] = w53;
  /* #200: @53 = (@12*@64) */
  w53  = (w12*w64);
  /* #201: @14 = (@14*@44) */
  w14 *= w44;
  /* #202: @53 = (@53-@14) */
  w53 -= w14;
  /* #203: @14 = @20[0] */
  for (rr=(&w14), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #204: @35 = (@14*@35) */
  w35  = (w14*w35);
  /* #205: @53 = (@53-@35) */
  w53 -= w35;
  /* #206: @43 = (@43*@15) */
  w43 *= w15;
  /* #207: @53 = (@53+@43) */
  w53 += w43;
  /* #208: @53 = (@53+@46) */
  w53 += w46;
  /* #209: @53 = (@53+@7) */
  w53 += w7;
  /* #210: output[0][9] = @53 */
  if (res[0]) res[0][9] = w53;
  /* #211: @13 = (@13*@44) */
  w13 *= w44;
  /* #212: @12 = (@12*@66) */
  w12 *= w66;
  /* #213: @13 = (@13-@12) */
  w13 -= w12;
  /* #214: @14 = (@14*@34) */
  w14 *= w34;
  /* #215: @13 = (@13+@14) */
  w13 += w14;
  /* #216: @40 = (@40*@15) */
  w40 *= w15;
  /* #217: @13 = (@13-@40) */
  w13 -= w40;
  /* #218: @13 = (@13+@47) */
  w13 += w47;
  /* #219: @13 = (@13+@6) */
  w13 += w6;
  /* #220: output[0][10] = @13 */
  if (res[0]) res[0][10] = w13;
  /* #221: @13 = (@10*@64) */
  w13  = (w10*w64);
  /* #222: @6 = (@11*@66) */
  w6  = (w11*w66);
  /* #223: @13 = (@13-@6) */
  w13 -= w6;
  /* #224: @13 = (@13+@48) */
  w13 += w48;
  /* #225: @13 = (@13+@5) */
  w13 += w5;
  /* #226: output[0][11] = @13 */
  if (res[0]) res[0][11] = w13;
  /* #227: @11 = (@11*@44) */
  w11 *= w44;
  /* #228: @64 = (@9*@64) */
  w64  = (w9*w64);
  /* #229: @11 = (@11-@64) */
  w11 -= w64;
  /* #230: @11 = (@11+@49) */
  w11 += w49;
  /* #231: @11 = (@11+@4) */
  w11 += w4;
  /* #232: output[0][12] = @11 */
  if (res[0]) res[0][12] = w11;
  /* #233: @9 = (@9*@66) */
  w9 *= w66;
  /* #234: @10 = (@10*@44) */
  w10 *= w44;
  /* #235: @9 = (@9-@10) */
  w9 -= w10;
  /* #236: @9 = (@9+@50) */
  w9 += w50;
  /* #237: @9 = (@9+@3) */
  w9 += w3;
  /* #238: output[0][13] = @9 */
  if (res[0]) res[0][13] = w9;
  /* #239: output[0][14] = @51 */
  if (res[0]) res[0][14] = w51;
  /* #240: @20 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w20);
  /* #241: @51 = dot(@20, @25) */
  w51 = casadi_dot(3, w20, w25);
  /* #242: @74 = zeros(5x1) */
  casadi_clear(w74, 5);
  /* #243: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #244: @25 = 
  [[378.788, 00, 00], 
   [00, 378.788, 00], 
   [00, 00, 201.613]] */
  casadi_copy(casadi_c3, 3, w25);
  /* #245: @27 = @25' */
  casadi_trans(w25,casadi_s0, w27, casadi_s0, iw);
  /* #246: @20 = mac(@27,@24,@20) */
  casadi_mtimes(w27, casadi_s0, w24, casadi_s1, w20, casadi_s1, w, 0);
  /* #247: (@74[1:4] += @20) */
  for (rr=w74+1, ss=w20; rr!=w74+4; rr+=1) *rr += *ss++;
  /* #248: {@9, @3, @50, @10, @44} = vertsplit(@74) */
  w9 = w74[0];
  w3 = w74[1];
  w50 = w74[2];
  w10 = w74[3];
  w44 = w74[4];
  /* #249: @51 = (@51+@9) */
  w51 += w9;
  /* #250: output[0][15] = @51 */
  if (res[0]) res[0][15] = w51;
  /* #251: output[0][16] = @3 */
  if (res[0]) res[0][16] = w3;
  /* #252: output[0][17] = @50 */
  if (res[0]) res[0][17] = w50;
  /* #253: output[0][18] = @10 */
  if (res[0]) res[0][18] = w10;
  /* #254: @26 = (@26+@44) */
  w26 += w44;
  /* #255: output[0][19] = @26 */
  if (res[0]) res[0][19] = w26;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 549;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
